export default {
    userResObtainCode:"h/1.0/checkMobile.json",//用户注册获取验证码接口
    userRegister:"h/1.0/register.json",//用户注册
    userLogin:"h/1.0/login.json",//用户登录
    pullUserData:"h/1.0/mineInfo.json",//个人中心信息
    classificationData:"h/1.0/fetchCates.json",//分类数据
    collectGoodsAddress:"h/1.0/consignee.json",//收货地址
    textAddress:"h/1.0/login.json",//test页面的地址，我也不知道什么接口的
    advertisementPicInterface:"h/1.0/homeBanner.json",//产品广告图数据接口
    commodityDetailsInterface:"h/1.0/fetchItemsInfo.json",//商品详情接口
    recommendedBrand:"h/1.0/categoryBanner.json",//推荐品牌
    shopList:"h/1.0/listItems.json",//商品列表数据
    shopCartList:"h/1.0/oCartItems.json",//购物车数据
    shopListBrand:"h/1.0/fetchBrands.json",//品牌渲染
    shopListCategory:"h/1.0/fetchCatesByParams.json",//品类渲染
    addShopCard:"h/1.0/addCart.json",//加入购物车|
    confirmationOfOrder:"h/1.0/confirmOrder.json",//确认订单商品渲染
    createAnOrder:"h/1.0/hOrder.json",//创建订单
    saveAddress:"/h/1.0/consignee.json",//保存收货地址
    orderData:"h/1.0/fetchTrades.json",//订单数据
    cancellationOfOrder:"h/1.0/cancelOrder.json",//取消订单
    otherInterface:"h/1.0/fetchTrade.json",//其他，不知道是什么接口，应该和订单有关
    wxPayment:"h/1.0/hwxPay.json",//微信支付
    alipayPayment:"m/1.0/order.json",//支付宝支付
    myRedBag:"h/1.0/fetchCouponList.json",//我的红包
    fetchPointList:"h/1.0/fetchPointList.json",//我的积分
    getMyWallet:"h/1.0/getMyWallet.json",//我的钱包
    profileProfit:"h/1.0/profileProfit.json",//资金报表
    salesRecordList:"h/1.0/salesRecordList.json",//余额明细
    getReturnGoodsVOList:"h/1.0/getReturnSaleRecordVOList.json",//获取全部退货退款列表(包括可退货和退货列表)
    reqGetPay:"h/1.0/reqGetPay.json",//申请提现数据
    myInOrDirectAlly:"h/1.0/myInOrDirectAlly.json",//我的粉丝接口
    searchItems:"h/1.0/searchItems.json",//分类搜索接口
    wxjssdkParam:"h/1.0/hjsApiParams.json",//获取微信JS-SDK,config时所需要的参数
    inviteAllyQrPage:"h/1.0/qrUrl.json",//生成二维码
    myParentUser:"h/1.0/myParentUser.json",//判断代理和等级
    getPayList:"h/1.0/getPayList.json",//体现明细
    logOut:"h/1.0/logOut.json",//退出登录
    appOrderDown:"m/1.0/order.json",//app支付宝下订单
    appWxOrderDown:"m/1.0/appWxOrder.json",//app微信下订单
    searchLogisticsCallBack:"h/1.0/searchLogisticsCallBack.json",//查看物流信息
    sureOrder:"m/1.0/sureOrder.json",//确认订单
    uploadCommentPic:"h/1.0/uploadCommentPic.json",//单张图片上传
    uploadCommentPics:"h/1.0/uploadCommentPics.json",//多张张图片上传
    addComments:"h/1.0/addComments.json",//评论
}  